# Generated by Django 5.1.3 on 2025-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_registrationrequest_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniVerificationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(max_length=50)),
                ('graduation_year', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('student_id_score', models.IntegerField(default=0)),
                ('graduation_year_score', models.IntegerField(default=0)),
                ('linkedin_score', models.IntegerField(default=0)),
                ('document_score', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('auto_approved', 'Auto Approved'), ('manual_review', 'Manual Review Required'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('auto_approval_threshold', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
