# Generated by Django 5.1.3 on 2025-10-14 19:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_mentorprofile_mentorshiprequest_mentorshipsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room (2 students)'), ('dormitory', 'Dormitory (4 students)')], default='double', max_length=20)),
                ('capacity', models.IntegerField(default=2)),
                ('current_occupancy', models.IntegerField(default=0)),
                ('floor', models.IntegerField(default=1)),
                ('has_attached_bathroom', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('target_audience', models.CharField(choices=[('all', 'All Residents'), ('current', 'Current Residents Only'), ('alumni', 'Alumni Only'), ('specific', 'Specific Group')], default='all', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='HostelResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='residents/')),
                ('father_name', models.CharField(max_length=255)),
                ('father_rank', models.CharField(max_length=100)),
                ('father_unit', models.CharField(max_length=255)),
                ('service_number', models.CharField(blank=True, max_length=50, null=True)),
                ('priority_category', models.CharField(choices=[('priority_1', 'Priority I - Battle Casualties/Gallantry Awardees'), ('priority_2', 'Priority II - NCR Posted/Coaching'), ('priority_3', 'Priority III - Ex-Servicemen Sons')], max_length=20)),
                ('college_name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField()),
                ('expected_graduation', models.DateField()),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active Resident'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('graduated', 'Graduated/Left')], default='active', max_length=20)),
                ('lg_name', models.CharField(max_length=255, verbose_name='Local Guardian Name')),
                ('lg_phone', models.CharField(max_length=20, verbose_name='Local Guardian Phone')),
                ('lg_address', models.TextField(verbose_name='Local Guardian Address')),
                ('lg_relation', models.CharField(max_length=100, verbose_name='Relation with Local Guardian')),
                ('admission_form', models.FileField(blank=True, null=True, upload_to='documents/admission/')),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='documents/id_proof/')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='documents/medical/')),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.hostelroom')),
            ],
        ),
    ]
