# Generated by Django 5.1.3 on 2026-02-03 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_resourcecategory_blog_is_public_event_is_public_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='category',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_public',
        ),
        migrations.DeleteModel(
            name='ResourceCategory',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
